package edu.jncl.siwaunal1.modelo;
// Generated Aug 31, 2016 1:34:36 PM by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Programa generated by hbm2java
 */
@Entity
@Table(name = "programa", schema = "public")
public class Programa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idprograma;
	private String nombre;
	private Character estado;
	private Set<Sede> sedes = new HashSet<Sede>(0);
	private Set<Aspirante> aspirantes = new HashSet<Aspirante>(0);

	public Programa() {
	}

	public Programa(int idprograma) {
		this.idprograma = idprograma;
	}

	public Programa(int idprograma, String nombre, Character estado, Set<Sede> sedes, Set<Aspirante> aspirantes) {
		this.idprograma = idprograma;
		this.nombre = nombre;
		this.estado = estado;
		this.sedes = sedes;
		this.aspirantes = aspirantes;
	}

	@Id

	@Column(name = "idprograma", unique = true, nullable = false)
	public int getIdprograma() {
		return this.idprograma;
	}

	public void setIdprograma(int idprograma) {
		this.idprograma = idprograma;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "programasede", schema = "public", joinColumns = {
			@JoinColumn(name = "idprogramacomp", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "idsedecomp", nullable = false, updatable = false) })
	public Set<Sede> getSedes() {
		return this.sedes;
	}

	public void setSedes(Set<Sede> sedes) {
		this.sedes = sedes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "programa")
	public Set<Aspirante> getAspirantes() {
		return this.aspirantes;
	}

	public void setAspirantes(Set<Aspirante> aspirantes) {
		this.aspirantes = aspirantes;
	}

}
