package edu.jncl.siwaunal1.modelo;
// Generated Aug 31, 2016 1:34:36 PM by Hibernate Tools 4.3.4.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name = "sede", schema = "public")
public class Sede implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idsede;
	private String nombre;
	private Double longitud;
	private Double latitud;
	private Character estado;
	private Integer idciudad;
	private Set<Aspirante> aspirantes = new HashSet<Aspirante>(0);
	private Set<Programa> programas = new HashSet<Programa>(0);

	public Sede() {
	}

	public Sede(int idsede) {
		this.idsede = idsede;
	}

	public Sede(int idsede, String nombre, Double longitud, Double latitud, Character estado, Integer idciudad,
			Set<Aspirante> aspirantes, Set<Programa> programas) {
		this.idsede = idsede;
		this.nombre = nombre;
		this.longitud = longitud;
		this.latitud = latitud;
		this.estado = estado;
		this.idciudad = idciudad;
		this.aspirantes = aspirantes;
		this.programas = programas;
	}

	@Id

	@Column(name = "idsede", unique = true, nullable = false)
	public int getIdsede() {
		return this.idsede;
	}

	public void setIdsede(int idsede) {
		this.idsede = idsede;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "longitud", precision = 17, scale = 17)
	public Double getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Double longitud) {
		this.longitud = longitud;
	}

	@Column(name = "latitud", precision = 17, scale = 17)
	public Double getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Double latitud) {
		this.latitud = latitud;
	}

	@Column(name = "estado", length = 1)
	public Character getEstado() {
		return this.estado;
	}

	public void setEstado(Character estado) {
		this.estado = estado;
	}

	@Column(name = "idciudad")
	public Integer getIdciudad() {
		return this.idciudad;
	}

	public void setIdciudad(Integer idciudad) {
		this.idciudad = idciudad;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sede")
	public Set<Aspirante> getAspirantes() {
		return this.aspirantes;
	}

	public void setAspirantes(Set<Aspirante> aspirantes) {
		this.aspirantes = aspirantes;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "programasede", schema = "public", joinColumns = {
			@JoinColumn(name = "idsedecomp", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "idprogramacomp", nullable = false, updatable = false) })
	public Set<Programa> getProgramas() {
		return this.programas;
	}

	public void setProgramas(Set<Programa> programas) {
		this.programas = programas;
	}

}
